package com.nonBlocking.common;

public interface ErrorCode extends CommonErrorCodeRange {
    int PARSING_ERROR = ERROR + 1000;
    int TIME_PARSING_ERROR = PARSING_ERROR + 100;
    int FILE_PARSING_ERROR = PARSING_ERROR + 200;

    int DATA_ERROR = ERROR + 2000;
    int DATA_ALREADY_ERROR = DATA_ERROR + 100;
    int DATA_NOT_ALLOWED_ERROR = DATA_ERROR + 200;
    int DATA_NOT_REGIST_ERROR = DATA_ERROR + 300;
    int DATA_EMPTY_ERROR = DATA_ERROR + 400;

    int ENCRYPT_ERROR = ERROR + 3000;
    int ENCRYPT_ALGORITHM_ERROR = ENCRYPT_ERROR + 100;
    int ENCRYPT_AES256_ERROR = ENCRYPT_ERROR + 200;
    int ENCRYPT_AES256_ENCRYPT_ERROR = ENCRYPT_AES256_ERROR + 10;
    int ENCRYPT_AES256_DEENCRYPT_ERROR = ENCRYPT_AES256_ERROR + 20;

    int CONNECTION_ERROR = ERROR + 4000;;
}
